In [ ]:
# problem 1
import numpy as np
arr = np.random.randint(1,50,(5,4)) 


[[ 6 45  7 35]
 [32 13 35  4]
 [43 21 25 21]
 [23 26 40 10]
 [39  7 37 10]]


In [ ]:
#(1)
print(arr)
diagonal_elements = np.diag(np.fliplr(arr))# directly by flipping the array 
# code wise
# for i in range(len(arr)):
#   for j in range(len(arr[i])):
#     if(i+j==3):
#       print('diagonal element',i,arr[i][j])

print(diagonal_elements)

[[ 6 45  7 35]
 [32 13 35  4]
 [43 21 25 21]
 [23 26 40 10]
 [39  7 37 10]]
diagonal element 0 35
diagonal element 1 35
diagonal element 2 21
diagonal element 3 23
[35 35 21 23]


In [10]:
#(2)
arr_max = np.max(arr, axis = 1)
print(arr_max)

[45 35 43 40 39]


In [ ]:
#(3)
arr_mean  = np.mean(arr)
new_arr = []
for i in range(len(arr)):
  int_arr = []
  for j in range(len(arr[i])):
    if(arr[i][j] <= arr_mean):
      int_arr.append(arr[i][j])
  new_arr.append(int_arr)
print(arr_mean)
print(new_arr)# this is what i thought like i didnt know if its now less than mean then what should we do so i thought this is the best we can do
# mean_value = np.mean(arr)
# result = arr[arr <= mean_value]
# print(result) this is the other method which gives a list of all the number in the 

23.95
[[6, 7], [13, 4], [21, 21], [23, 10], [7, 10]]
[ 6  7 13  4 21 21 23 10  7 10]


In [ ]:
import numpy as np

def numpy_boundary_traversal(matrix):
    if matrix.ndim != 2:
        raise ValueError("Input must be a 2D NumPy array.")

    rows, cols = matrix.shape
    boundary = []

    # Top row
    for j in range(cols):
        boundary.append(matrix[0, j])

    # Right column (excluding top and bottom corners)
    for i in range(1, rows - 1):
        boundary.append(matrix[i, cols - 1])

    # Bottom row (if more than 1 row)
    if rows > 1:
        for j in range(cols - 1, -1, -1):
            boundary.append(matrix[rows - 1, j])

    # Left column (excluding top and bottom corners)
    if cols > 1:
        for i in range(rows - 2, 0, -1):
            boundary.append(matrix[i, 0])

    return boundary
# def boundary__traversal(matrix):
#     boundary = []
#     for i in range(len(matrix)):
#       print(i,'h')
#       for j in range(len(matrix[i])):
#           if(i==0 or i == len(matrix)-1):
#             print(i)
#             boundary.append(matrix[i][j])
#           elif((j == 0 or (j == len(matrix[i])-1)) and (i != 0 or (i != len(matrix)-1))):
#               print(i,'j')
#               boundary.append(matrix[i][j])
#     return boundary
# matri = np.array([[1,2,3],[3,4,5],[4,5,6],[8,9,0]])
# bnd = boundary__traversal(matri)
# tnd = numpy_boundary_traversal(matri)
# print(bnd)
# print(tnd)
# these are two ways in which we can make one is row wise an other is normal 

0 h
0
0
0
1 h
1 j
1 j
2 h
2 j
2 j
3 h
3
3
3
[1, 2, 3, 3, 5, 4, 6, 8, 9, 0]
[1, 2, 3, 5, 6, 0, 9, 8, 4, 3]


In [ ]:
# problem 2


arr = np.random.uniform(0, 10, 20)




Original Array:
[3.1929848  3.34039049 5.95327877 4.33800893 7.69794769 9.1339712
 6.43748533 8.00421521 2.55552358 3.49216551 9.06745526 0.56806774
 0.16383741 5.90886207 4.47242337 8.91890032 4.49470836 1.48353552
 5.67919757 7.56988039]


In [50]:
#(1)
print(arr)
arr_round = np.round(arr,2)
print(arr_round)

[3.1929848  3.34039049 5.95327877 4.33800893 7.69794769 9.1339712
 6.43748533 8.00421521 2.55552358 3.49216551 9.06745526 0.56806774
 0.16383741 5.90886207 4.47242337 8.91890032 4.49470836 1.48353552
 5.67919757 7.56988039]
[3.19 3.34 5.95 4.34 7.7  9.13 6.44 8.   2.56 3.49 9.07 0.57 0.16 5.91
 4.47 8.92 4.49 1.48 5.68 7.57]


In [51]:
#(2)
arr_min = np.min(arr_round)
arr_max = np.max(arr_round)
arr_median = np.median(arr_round)
print(arr_min)
print(arr_max)
print(arr_median)


0.16
9.13
5.085


In [52]:
#(3)
arr_round[arr_round<5] = arr_round[arr_round<5]**2
arr_round = np.round(arr_round,2)
print(arr_round)

[10.18 11.16  5.95 18.84  7.7   9.13  6.44  8.    6.55 12.18  9.07  0.32
  0.03  5.91 19.98  8.92 20.16  2.19  5.68  7.57]


In [53]:
#(4)
def numpy_alternate_sort(array):
    sorted_array = np.sort(array)
    
    
    result = []
    start, end = 0, len(sorted_array) - 1
    
    # Alternate between smallest and largest
    while start <= end:
        result.append(sorted_array[start])
        start += 1
        if start <= end:
            result.append(sorted_array[end])
            end -= 1

    return np.array(result)
alt_sort = numpy_alternate_sort(arr_round)
print(alt_sort)

[ 0.03 20.16  0.32 19.98  2.19 18.84  5.68 12.18  5.91 11.16  5.95 10.18
  6.44  9.13  6.55  9.07  7.57  8.92  7.7   8.  ]


In [60]:
#problem 3
import pandas as pd
import numpy as np

# Sample data
names = ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ivan', 'Jane']
subjects = ['Math', 'English', 'Science', 'Math', 'English', 'Science', 'Math', 'English', 'Science', 'Math']

# Create DataFrame
df = pd.DataFrame({
    'Name': names,
    'Subject': subjects,
    'Score': np.random.randint(50, 101, size=10),
    'Grade': ''  # initially empty
})


In [75]:
#(1)
# Assign grades
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(assign_grade)
# or

# grades = []
# for score in df['Score']:
#     grades.append(assign_grade(score))
# df['Grade'] = grades
df.head()

Name  Subject  Score Grade
0    Alice     Math     69     D
1      Bob  English     98     A
2  Charlie  Science    100     A
3    David     Math     92     A
4      Eva  English     90     A

In [76]:
#(2)
#  Print DataFrame sorted by Score in descending order
print("Sorted by Score (descending):")
print(df.sort_values(by='Score', ascending=False))

Sorted by Score (descending):
      Name  Subject  Score Grade
2  Charlie  Science    100     A
1      Bob  English     98     A
7    Helen  English     97     A
3    David     Math     92     A
4      Eva  English     90     A
5    Frank  Science     88     B
9     Jane     Math     82     B
6    Grace     Math     73     C
0    Alice     Math     69     D
8     Ivan  Science     55     F


In [63]:
#(3)
# Calculate and print average score for each subject
print("\nAverage score by subject:")
print(df.groupby('Subject')['Score'].mean())


Average score by subject:
Subject
English    95.0
Math       79.0
Science    81.0
Name: Score, dtype: float64


In [64]:
#(4)
#  Function to filter grades A or B
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

# Filter and display
print("\nStudents with Grade A or B:")
print(pandas_filter_pass(df))


Students with Grade A or B:
      Name  Subject  Score Grade
1      Bob  English     98     A
2  Charlie  Science    100     A
3    David     Math     92     A
4      Eva  English     90     A
5    Frank  Science     88     B
7    Helen  English     97     A
9     Jane     Math     82     B


In [ ]:
#problem 4
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

#. Create synthetic dataset
positive_reviews = ["I loved the movie!", "Amazing story and acting.", "Great direction.", "Absolutely fantastic!", 
                    "It was a beautiful film.", "Highly recommended!", "Enjoyed every minute.", "Brilliant work!", 
                    "Such a heartfelt story.", "Well made and touching."] * 5

negative_reviews = ["I hated the movie.", "Terrible acting and story.", "Worst film ever.", "Completely boring.", 
                    "Not worth the time.", "I regret watching it.", "Bad direction.", "Poorly executed.", 
                    "Waste of time.", "Unwatchable and dull."] * 5

# Combine into DataFrame
reviews = pd.DataFrame({
    "Review": positive_reviews + negative_reviews,
    "Sentiment": ["positive"] * 50 + ["negative"] * 50
})
reviews.head()


Review Sentiment
0         I loved the movie!  positive
1  Amazing story and acting.  positive
2           Great direction.  positive
3      Absolutely fantastic!  positive
4   It was a beautiful film.  positive

In [78]:
# 1. Tokenize with CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=500)
X = vectorizer.fit_transform(reviews['Review'])
y = reviews['Sentiment']



In [79]:
# 2. Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [90]:
# 3. Train Naive Bayes classifier
from sklearn.metrics import classification_report
model = MultinomialNB()
model.fit(X_train, y_train)

# Accuracy
y_pred = model.predict(X_test)
print("Test Set Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))


Test Set Accuracy: 0.72
              precision    recall  f1-score   support

         bad       0.53      1.00      0.70         8
        good       1.00      0.59      0.74        17

    accuracy                           0.72        25
   macro avg       0.77      0.79      0.72        25
weighted avg       0.85      0.72      0.73        25



In [84]:
# 4 Prediction function
def predict_review_sentiment(model, vectorizer, review):
    review_vec = vectorizer.transform([review])
    return model.predict(review_vec)[0]

# Example prediction
print("Predicted sentiment:", predict_review_sentiment(model, vectorizer, "That movie was not teribble"))

Predicted sentiment: positive


In [85]:

# problem 5
import random

# Generate synthetic data
texts = []
labels = []

positive_samples = ["This product is amazing!", "I loved it!", "Great value for money.",
                    "Fantastic quality.", "Highly recommend.", "Very satisfied.", 
                    "Exceeded my expectations.", "Superb build.", "Delighted!", "Impressive!"]

negative_samples = ["Terrible product.", "Very disappointed.", "Would not recommend.",
                    "It broke after a day.", "Poor quality.", "Not worth the money.",
                    "Completely useless.", "Unsatisfactory.", "Bad experience.", "Low quality."]

# Create 100 samples: 50 good, 50 bad
for _ in range(50):
    texts.append(random.choice(positive_samples))
    labels.append('good')

for _ in range(50):
    texts.append(random.choice(negative_samples))
    labels.append('bad')

# Shuffle the dataset
data = pd.DataFrame({'Text': texts, 'Label': labels}).sample(frac=1, random_state=42).reset_index(drop=True)


In [ ]:
#(1)
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(data['Text'])
y = data['Label']


In [ ]:
#(2)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)


In [88]:
#(3)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Print precision, recall, and F1-score
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

         bad       0.53      1.00      0.70         8
        good       1.00      0.59      0.74        17

    accuracy                           0.72        25
   macro avg       0.77      0.79      0.72        25
weighted avg       0.85      0.72      0.73        25



In [89]:
#(4)
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)
